[package]
name = "hekit"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
shlex = "1"
glob = "0.3"
regex = "1"
zip = "0.6"
tar = "0.4"
flate2 = "1"
bzip2 = "0.4"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }
